# src/config.py

# --- APP CONFIGURATION ---
PATIENT_ID = "PT-001"

# --- EMA FILTERING ---
SMOOTHING_ALPHA = 0.25
MAX_MISSING_FRAMES = 6

# --- MEDIAPIPE CONFIGURATION ---
MP_MODEL_PATH = 'pose_landmarker_full.task'
MP_MIN_DETECTION_CONFIDENCE = 0.55
MP_MIN_TRACKING_CONFIDENCE = 0.5

# --- QC THRESHOLDS ---
QC_LIGHTING_MIN_BRIGHTNESS = 80
QC_LIGHTING_MAX_BRIGHTNESS = 220
QC_OCCLUSION_VISIBILITY_THRESHOLD = 0.6

# --- A4 CALIBRATION ---
A4_REAL_HEIGHT_M = 0.297
A4_MIN_CONTOUR_AREA = 10000
A4_MIN_ASPECT_RATIO = 1.3
A4_MAX_ASPECT_RATIO = 1.5
CALIBRATION_EMA_ALPHA = 0.1
